spring:
  application:
    name: e-commerce-app
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: anarftliyev@gmail.com
    password: fvgi gbyu dnsl byjb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
    level:
        root: DEBUG
        com.example.ecommerceapp: DEBUG

springdoc:
  server-url: http://localhost:8080

cloudinary:
  cloud-name: dmysg4p06
  api-key: 355513464313338
  api-secret: qTPd1H4rwh-Ha9qsFu9abr8lRFE
  upload-folder: e-commerce-app/images

