spring:
  datasource:
    url: jdbc:postgresql://db:5432/ecommerce
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  server-url: http://localhost:8080
